gateway:
  name: "edcv-gateway"
  namespace: "edc-v"
  hostnames:
    - cxve.localhost
  pathPrefix: /api/certo

sigletBaseUrl: "http://cxve.localhost/api/siglet"

database:
  url:  jdbc:postgresql://core-platform-postgresql.edc-v.svc.cluster.local:5432/certo
  username: certo
  password: certo
  # the certo chart already creates a secret, so we only need to reference it
  existingSecretKey: password
  ddlAuto: "update"

image:
  tag: "latest"

