package com.metaform.cxve.domain.model;

public enum DocumentTypeId {
    CX_FRAME_CONTRACT,
    COMMERCIAL_REGISTER_EXTRACT,
    APP_CONTRACT,
    CONFORMITY_APPROVAL_REGISTRATION,
    ADDITIONAL_DETAILS,
    APP_LEADIMAGE,
    APP_IMAGE,
    SELF_DESCRIPTION,
    APP_TECHNICAL_INFORMATION,
    CONFORMITY_APPROVAL_CONNECTOR,
    CONFORMITY_APPROVAL_BUSINESS_APPS,
    CONFORMITY_APPROVAL_SERVICES,
    SERVICE_LEADIMAGE,
    PRESENTATION,
    COMPANY_CERTIFICATE
}
